### ISSUE TITLE
Import metadata from spreadsheets

### ISSUE THREAD

**Issue by ceteri** [NYU-CI/RCPublications#60]
One recurring issue that costs us much time is the matter of unicode character set handling. 

The process of manual cut&paste from spreadsheets introduces character set issues, which create errors during API lookups later in the workflow.

We need to read spreadsheets (Excel or Google docs) programmatically and convert into the required form (JSON? CSV?) with proper handling through codecs.

For example, here's a library for programmatically reading Excel:
  - <https://openpyxl.readthedocs.io/en/stable/>

Be sure to use the `codecs` examples in `RCGraph` to ensure that unicode characters get handled correctly.

**Comment by lobodemonte** [comment]
Hey Paco, 

Have you seen any issues lately with the latest batch of publications? 

I brought up to Sophie two weeks ago that when we generate the CSVs with Python, we need to specify the encoding as "utf-8-sig" at the time of creating the CSV because Excel has this issue where if it doesn't see a byte order mark it will decode special characters incorrectly. 

I noticed that once CSVs were generated using "utf-8-sig", I no longer had saw any bad decoding on Excel. 

https://stackoverflow.com/questions/25788037/pandas-df-to-csvfile-csv-encode-utf-8-still-gives-trash-characters-for-min/43684587#43684587

**Comment by ceteri** [comment]
@lobodemonte That's excellent! No, we haven't been seeing unicode character issues recently. I need to run a full workflow soon and double-check.

Do we have the capability then to read and ingest Excel spreadsheet programmatically to generate the CSVs?

**Comment by lobodemonte** [comment]
The issue came when we would save API search results into CSVs (for later validation), once we would open the CSVs with Excel, then the unicode issue would be introduced after Saving. 
Sophie would always create the python code used for searching and creating the CSVs, so as long as we remember to use "utf-8-sig" we should be fine.

**Comment by lobodemonte** [comment]
I'm going to go ahead and close this since the issue was identified.
The solution seems to always specify encoding as utf-8-sig when saving data as a CSV in python
