### ISSUE TITLE
improper metadata

### ISSUE THREAD

**Issue by ceteri** [NYU-CI/RCPublications#8]
> "title": "WIC Households' Food Purchases Using WIC Benefits and Paying Out of Pocket: A Case Study of Cold Cereal Purchases",

this publication's metadata has problems:

- bad `url -- multiple values, there should only be one
- bad `doi` -- multiple values, there should only be one, value should be `10.22004/ag.econ.262197` ?
- `pub_url` field should be `pdf` ?

**Comment by srand525** [comment]
hi paco, yup, there is some invalid metadata in this one. it traces back to curated linkages from the data provider - see here (https://github.com/NYU-CI/RichContextMetadata/blob/master/metadata/20190619_usda_foodaps/foodaps_usda_cleaned.csv) - it looks like they used 'doi' as a general column - they do store identifiers in some of the cells. my thinking was that this would get weeded out downstream, with unit tests around the same place where we reconcile metadata from APIs. Let's discuss today!

**Comment by srand525** [comment]
That issue comes from here:
https://github.com/NYU-CI/RichContextMetadata/blob/master/metadata/20190610_usda_iri/iri_dataset_linkages.csv

some of the links under url are pdfs, some are not (e.g. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4427330/ is not). my understanding is that elements in the `original` dict were to be handled downstream of the publication of partitions.

This title also exists in numerous partitions like 
[here](https://github.com/NYU-CI/RCPublications/blob/1adfd4c1ea92e6ba39e932632c1c36ae05c2100c/partitions/20190619_usda_foodaps_publications.json) and [here](https://github.com/NYU-CI/RCPublications/blob/4aa8d1e9f79c4635550d54833dbef576221c3d29/partitions/20190610_usda_iri_publications.json) and [here](https://github.com/NYU-CI/RCPublications/blob/bcdaec637852d36073e189695f480634e23bdeb2/partitions/20190913_usda_excel_publications.json).

**Comment by srand525** [comment]
Fixed - see [here](https://github.com/NYU-CI/RCPublications/blob/master/partitions/20190610_usda_iri_publications.json) and [here](https://github.com/NYU-CI/RCPublications/blob/master/partitions/20190619_usda_foodaps_publications.json)

**Comment by ceteri** [comment]
Thanks for fixing that -

Some kinds of metadata errors can be fixed downstream, but others introduce problems that should be caught during unit tests upstream.  For example, if there's a web page URL listed instead of where a DOI is expected, that means now we must add extra testing downstream. That accumulates at tech debt over time.

Also, there are fields here which have `NaN` instead of a string value.  Technically speaking, that's not valid JSON -- and also means we must add extra tests downstream. If there's a field (e.g., "url" or "pdf") which is supposed to be a string, then it should either have a string or `null` to be valid JSON.  The way that we're managing metadata, it's better to omit an optional field (such as in `original`) than to have lots of `null` fields.

We'll catch this additional issue (`NaN` in place of string) in a later PR.
